[ADD]상품리스트 뷰 추가
wecode-bootcamp-korea/14-2nd-2.9cm-backend pull request #4
Opened 2020-12-05 12:52 UTC by 097kim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
상품리스트 뷰 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
많은 사랑과 관심은 부드럽게
회초리는 강력하게

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-05 13:05 UTC, dooyeonk commented on store/views.py
> +from django.db.models import Q
파이썬 모듈
장고 모듈
자체적으로 사용하는 모듈
순으로 한칸씩 띄워서 컨벤션 맞춰주세용!

2020-12-05 13:37 UTC, 097kim commented on store/views.py
> +from django.db.models import Q
아앗.. 야레야레.. 메모..

2020-12-05 13:42 UTC, dooyeonk commented on .vscode/settings.json
> +}
에디터 관련 파일은 gitignore에 추가해주시고 git rm --cached 사용하셔서 지워주세요!

2020-12-05 13:52 UTC, 097kim commented on .vscode/settings.json
> +}
아앗.. 메모..

2020-12-05 14:59 UTC, jamessoun93 requested changes

2020-12-05 14:59 UTC, jamessoun93 commented on .vscode/settings.json
> +}
@dooyeonk 👍

2020-12-05 14:59 UTC, jamessoun93 commented on store/views.py
> +
일단 코드 순서대로 정리를 해보자면,
1. `brand` 라는 `key` 로 들어오는 쿼리 파라미터를 읽어들인다.
2. 읽어들인 결과를 기준으로 `filter` 처리를 한다.
3. `filter` 의 결과가 비어있는 `QuerySet` 일 시 프로덕트 전부를 가져와서 뿌려준다.

뭔가 이상하지 않나요?
프로덕트를 전부 가져오는 조건은 쿼리 파라미터로 아무것도 들어오지 않았을때 일텐데, 지금은 해당 브랜드 네임을 가진 `product` 가 없을 시 `product` 를 전부 가지고 오고있네요. 

의도하셨던 로직에 맞게 수정해보시고, 어려움이 있으시면 말씀해주세요~!

2020-12-06 01:36 UTC, 097kim commented on store/views.py
> +
넵 잘못돼도 단단히 잘못됐네요..
엉뚱한 곳에서 김서방을 찾고 있었네요.. 와하..;;
한번 수정 해보겠습니다..

2020-12-09 07:13 UTC, closed without merging